kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 6443
    hostPort: 6443
    listenAddress: "0.0.0.0"
- role: worker
  extraPortMappings:
  - containerPort: 80
    hostPort: 9080
    listenAddress: "0.0.0.0"
  - containerPort: 443
    hostPort: 9443
    listenAddress: "0.0.0.0"