#@ load("@ytt:data", "data")
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: "opa-cert"
  namespace: "opa"
spec:
  secretName: "opa-cert-tls"
  commonName: "opa.opa.svc"
  isCA: true
  dnsNames:
    - "opa-cert"
    - opa.opa.svc
    -  #@ data.values.opa.fqdn
  ipAddresses:
    - "127.0.0.1"
    - #@ data.values.opa.ip
  duration: "2160h0m0s"
  renewBefore: "360h0m0s"
  organization:
    - "vmware"
  keySize: 4096
  keyAlgorithm: "rsa"
  keyEncoding: "pkcs1"
  issuerRef:
    name: "selfsigned-issuer"
    kind: "ClusterIssuer"
